name: Run puppeteer automation

on: push

jobs:
  puppeteer:
    name: Puppeteer run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Use node version
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'

      - name: Run test
        run: |
          cd test
          npm install
          npm start
